id: I32D02C62
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T06:18:40+00:00'
last_modified: '2022-06-08T16:44:47.663456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18784
  title: བཅའ་ཁྲིམས་སློབ་པ་དང་ཀུན་སྤྱོད་གླེང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    B7F8:
      image_group_id: I8LS18786
      title: ''
      total_pages: 220
      order: 1
      base_file: B7F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
