id: P010678
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18784
  title: བཅའ་ཁྲིམས་སློབ་པ་དང་ཀུན་སྤྱོད་གླེང་བ།
  author: ''
  volumes:
    aee59f9768b8401dbb208cfd3a364d84:
      image_group_id: I8LS18786
      title: ''
      volume_number: 1
      total_pages: 220
      base_file: v001.txt
